version: "3"
services:
  whoami:
    image: jwilder/whoami
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=admin.lascuolaopensource.xyz
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=8000
        - com.df.letsencrypt.host=admin.lascuolaopensource.xyz
        - com.df.letsencrypt.email=info@lascuolaopensource.xyz
networks:
  proxy:
    external: true
