version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --ssl --sslcert /certs/live/pad.lascuolaopensource.xyz/cert.pem --sslkey /certs/live/pad.lascuolaopensource.xyz/privkey.pem
    ports:
      - "1234:9000"
      - "8000:8000"
    volumes:
      - /etc/letsencrypt:/certs
      - portainer_data:/data
    networks:
      - proxy
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceName=portainer
        - com.df.serviceDomain=pad.lascuolaopensource.xyz
        - com.df.servicePath=/
        - com.df.httpsPort=1234
        - com.df.srcHttpsPort=443
        - com.df.letsencrypt.host=pad.lascuolaopensource.xyz
        - com.df.letsencrypt.email=info@lascuolaopensource.xyz
networks:
  proxy:
    external: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
